### PR TITLE
Adding rpcstats code to Git

### PR DESCRIPTION
**Pull request by PriyankaGitCom**

### CODE REVIEW

**Comment by rjsparks** [comment]
Why did this go into the same repo as the website?
I would have expected it to go into its own repo in the rfc-editor repository - it would have its own set of issues/PRs.

**Comment by PriyankaGitCom** [comment]
Will add as a separate repository under rfc-editor.

**Comment by PriyankaGitCom** [comment]
Added rsestats as a separate repository.

**Comment by rjsparks** [comment]
You should remove it from this repo when you get a chance.

**Comment by PriyankaGitCom** [comment]
I will remove the foldewr rsestats when I am back on June 23.

**Pull request merged**
